POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "HoangHon",
  "password": "jim"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Test thêm chi phí thu bảo lãnh
POST http://localhost:5000/api/ChiPhiVon/insert
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFiZjg5ZDllNmU0NTJmNTAzMzM3NzciLCJpYXQiOjE2NjUwMDk3OTF9.xiTUc_Jam-ppJntkt3Vz-vC9c8l39KJKfdye793944M

{
  "giavon" : 537700000,
  "giaban" : 708600000,
  "giatridaura" : 779460000 ,
  "ngay": "06/7/2022",
  "diengiai": "Cần hỏi lại",
  "sotienKHtra":389730000,
  "sotienTTNTP":591470000,
  "sotienhangconno":201740000,
  "songay":30,
  "laisuat":0.08,
  "chiphilaivay":1326510 ,
  "ghichu": "Chú ý số tiền hàng còn nợ trước chưa có"
}

###test get chiphivon

GET http://localhost:5000/api/ChiPhiVon/view
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFiZjg5ZDllNmU0NTJmNTAzMzM3NzciLCJpYXQiOjE2NjU5MTU3NTZ9.K7uqHp3ztb3i0acZNMM1IE8HQ9gT2xfz-gDSqHWTtwY
###

PUT http://localhost:5000/api/ChiPhiVon/update/633ed08f24dd1d3d08059d4e
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFiZjg5ZDllNmU0NTJmNTAzMzM3NzciLCJpYXQiOjE2NjUwMDk3OTF9.xiTUc_Jam-ppJntkt3Vz-vC9c8l39KJKfdye793944M

{
  "giavon" : 1200000,
  "giaban" : 200000,
  "giatridaura" : 300000 ,
  "ngay": "06/08/2022",
  "diengiai": "Cần hỏi lại CẬP NHẬT",
  "sotienKHtra":1500000,
   //sotienTTNTP,
   //"sotienhangconno": 50000,
   "songay":2,
   "laisuat":0.08,
   //"chiphilaivay": ,
  "ghichu": "Chú ý số tiền hàng còn nợ trước chưa có"
}

###

DELETE http://localhost:5000/api/ChiPhiVon/delete/633ec6073a32e077a870879c
Authorization:  admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFiZjg5ZDllNmU0NTJmNTAzMzM3NzciLCJpYXQiOjE2NjUwMDk3OTF9.xiTUc_Jam-ppJntkt3Vz-vC9c8l39KJKfdye793944M


