POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "jim"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Test thêm chi phí thu bảo lãnh
POST http://localhost:5000/api/chiphithubaolanh/insert
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzAyYmM0ODE3MGJmYzBhYjQ4NTJiMTMiLCJpYXQiOjE2NjE2MDk5MzF9.ltsUiTzsFvqFUnFpj-VmCgxLYgNVf3nwJvd4RoIChTw

{
  "noidung": "BL dự thầu",
  "giatrithubaolanh": 360000000,
  "sothang": 3,
  "tilephi": 0.02,
  //thanhtien = 
  "ghichu": "Giá trị thu bao lanh"
}

###test get chiphithubaolanh

GET http://localhost:5000/api/chiphithubaolanh
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYzMGY4MTRhN2RhODNkYTQxZGMzY2EiLCJpYXQiOjE2NjEwODE3ODR9.83tehhtaxbIlDvvmSqEGRPYrmb_nIcHqrNus7pI3bLE
###

PUT http://localhost:5000/api/chiphithubaolanh/6302195d3b390d6e7c42d1fc
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYzMGY4MTRhN2RhODNkYTQxZGMzY2EiLCJpYXQiOjE2NjEwODE3ODR9.83tehhtaxbIlDvvmSqEGRPYrmb_nIcHqrNus7pI3bLE

{
  "noidung": "BL dự thầu erer CẬP NHẬT deeeeeeee",
  "giatrithubaolanh": 360000000,
  "sothang": 3,
  "tilephi": 0.02,
  //thanhtien = 
  "ghichu": "Giá trị thư bảo lãnh"
}

###

DELETE http://localhost:5000/api/chiphithubaolanh/6302195d3b390d6e7c42d1fc
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYzMGY4MTRhN2RhODNkYTQxZGMzY2EiLCJpYXQiOjE2NjEwODE3ODR9.83tehhtaxbIlDvvmSqEGRPYrmb_nIcHqrNus7pI3bLE

