POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "HoangHon",
  "password": "jim"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "HoangHon",
  "password": "jim"
}

###

POST http://localhost:5000/api/chiphikhac
Content-Type: application/json
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NjAwMjYxNTh9.k7hR1zdTrDe0jyTypzIga0fX1j5pMtXB6kVaiBvUOQg

{
  "noidung": "Nodejs4444",
  "sotien": 5000,
  "ghichu": "TO LEARN"
}

###

GET http://localhost:5000/api/chiphikhac
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NjAwMjYxNTh9.k7hR1zdTrDe0jyTypzIga0fX1j5pMtXB6kVaiBvUOQg

###

PUT http://localhost:5000/api/chiphikhac/62fe1a5af369450af479fac1
Content-Type: application/json
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NjAwMjYxNTh9.k7hR1zdTrDe0jyTypzIga0fX1j5pMtXB6kVaiBvUOQg

{
  "noidung": "Hop Dong Caapj nhaat",
  "sotien": 10000,
  "ghichu": "TO LEARN"
}


###

DELETE http://localhost:5000/api/chiphikhac/62fe1a5af369450af479fac1
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NjAwMjYxNTh9.k7hR1zdTrDe0jyTypzIga0fX1j5pMtXB6kVaiBvUOQg

