POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "HoangHon",
  "password": "jim"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "HoangHon",
  "password": "jim"
}

### Test thêm chi phí thu bảo lãnh
POST http://localhost:5000/api/chitiethanghoa/insert
Content-Type: application/json
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NTk3OTY3OTB9.zgU34WZI9r-xvlFvqJ3k47veTbD6fJSUQ5l3zbvgwlA

{
  "tenhang":"Cần có dữ liệu mẫu 2",
  "soluong": 10,
  "dongiaFOB":1000,
  "dongiakho":1200,
  //thanhtiengiakho, //cần tính
  "dongiaban":1500,
  //thanhtiengiaban, //cần tính
  "ghichu":"Còn thiếu Tổng tiền nhập kho và bán của hàng hóa"
}

###test get chiphithubaolanh

GET http://localhost:5000/api/chitiethanghoa
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NTk3OTY3OTB9.zgU34WZI9r-xvlFvqJ3k47veTbD6fJSUQ5l3zbvgwlA
###

PUT http://localhost:5000/api/chitiethanghoa/6309f1f2d1e37b4c606c9725
Content-Type: application/json
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NTk3OTY3OTB9.zgU34WZI9r-xvlFvqJ3k47veTbD6fJSUQ5l3zbvgwlA

{
  "tenhang":"Cần có dữ liệu mẫu CẬP NHẬT",
  "soluong": 2,
  "dongiaFOB":1000,
  "dongiakho":1200,
  //thanhtiengiakho, //cần tính
  "dongiaban":1500,
  //thanhtiengiaban, //cần tính
  "ghichu":"Còn thiếu Tổng tiền nhập kho và bán của hàng hóa"
}

###

DELETE http://localhost:5000/api/chitiethanghoa/6309f1f2d1e37b4c606c9725
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NTk3OTQzNzR9.eG_Ys9DqeY-7wAKjNqlLineYRPlpewNgNDuJS9_ISQM


