POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "HoangHon",
  "password": "jim"
}

### Login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Test thêm chi phí thu bảo lãnh
POST http://localhost:5000/api/mandaykysu/insert
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYzMGY4MTRhN2RhODNkYTQxZGMzY2EiLCJpYXQiOjE2NjE1ODY2MTl9.Kc2xhi-LBdQTaSE8la0RablzHyH_ebe5h2nWQ6lp4kg

{
  "phongban": "Phòng GP HT - Mạng",
  "mandaychuan": 60,
  "songuoi": 2,
  "songaythuchien": 5,
  //thanhtien = 
  "ghichu": "Phòng GP HT - Mạng"
}

###test get chiphithubaolanh

GET http://localhost:5000/api/mandaykysu
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NTk3OTY3OTB9.zgU34WZI9r-xvlFvqJ3k47veTbD6fJSUQ5l3zbvgwlA
###

PUT http://localhost:5000/api/mandaykysu/62ee802404d9fa12244d8e71
Content-Type: application/json
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NTk3OTY3OTB9.zgU34WZI9r-xvlFvqJ3k47veTbD6fJSUQ5l3zbvgwlA

{
  "phongban": "Phòng GP HT - Mạng CAP NHAT",
  "mandaychuan": 60,
  "songuoi": 2,
  "songaythuchien": 5,
  //thanhtien = 
  "ghichu": "Phòng GP HT - Mạng CAP NHAT "
}

###

DELETE http://localhost:5000/api/mandaykysu/62ee802404d9fa12244d8e71
Authorization: HoangHon eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmVlNTVmNmZhYzcyZTE0MjRhMGEyMTkiLCJpYXQiOjE2NTk3OTQzNzR9.eG_Ys9DqeY-7wAKjNqlLineYRPlpewNgNDuJS9_ISQM


