POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

POST http://localhost:5000/api/phongban/insert
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFiZjg5ZDllNmU0NTJmNTAzMzM3NzciLCJpYXQiOjE2NjM0NjU3ODJ9.yysgQJunVZ5jcv01SUMnFG8eeAl34z8i8iTQpwMF92A

{
  "Tenphongban": "Phòng GP Dữ Liệu HCM",
  "Mandaychuan": 62
}

###

GET http://localhost:5000/api/phongban/view
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFiZjg5ZDllNmU0NTJmNTAzMzM3NzciLCJpYXQiOjE2NjM0NjU3ODJ9.yysgQJunVZ5jcv01SUMnFG8eeAl34z8i8iTQpwMF92A

###

PUT http://localhost:5000/api/phongban/update/632679802a0e413d741a0f8a
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFiZjg5ZDllNmU0NTJmNTAzMzM3NzciLCJpYXQiOjE2NjM0NjU3ODJ9.yysgQJunVZ5jcv01SUMnFG8eeAl34z8i8iTQpwMF92A

{
  "Tenphongban": "Phòng GP HT - Mạng",
  "Mandaychuan": 60
}


###

DELETE http://localhost:5000/api/phongban/delete/6326811e3385705de452061c
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFiZjg5ZDllNmU0NTJmNTAzMzM3NzciLCJpYXQiOjE2NjM0NjU3ODJ9.yysgQJunVZ5jcv01SUMnFG8eeAl34z8i8iTQpwMF92A

