POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "123",
  "roleId": 0
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

POST http://localhost:5000/api/users
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYzMGY4MTRhN2RhODNkYTQxZGMzY2EiLCJpYXQiOjE2NjE5MzAxMDN9.SCaKkB3kv9IApejYDrDI7L4ilWBrOjNa8k0MreJ4Coo

{
  "username": "testadd",
  "password": "123"
}

###

GET http://localhost:5000/api/users
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYzMGY4MTRhN2RhODNkYTQxZGMzY2EiLCJpYXQiOjE2NjE5MzAxMDN9.SCaKkB3kv9IApejYDrDI7L4ilWBrOjNa8k0MreJ4Coo

###

PUT http://localhost:5000/api/users/630f150382c6d080b8563f04
Content-Type: application/json
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYzMGY4MTRhN2RhODNkYTQxZGMzY2EiLCJpYXQiOjE2NjE5MzAxMDN9.SCaKkB3kv9IApejYDrDI7L4ilWBrOjNa8k0MreJ4Coo

{
  "username": "testadd",
  "password": "135"
}


###

DELETE http://localhost:5000/api/users/630f13554e3223673c292ed7
Authorization: admin eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYzMGY4MTRhN2RhODNkYTQxZGMzY2EiLCJpYXQiOjE2NjE5MzAxMDN9.SCaKkB3kv9IApejYDrDI7L4ilWBrOjNa8k0MreJ4Coo

